apiVersion: v1
kind: Service
metadata:
  name: openid
  labels:
    name: openid
spec:
  ports:
    - port: 4444
      targetPort: 10141
    - port: 4445
      targetPort: 10142
  selector:
      name: openid
