apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    name: nextcloud
spec:
  ports:
    - port: 80
      targetPort: 10131
    - port: 443
      targetPort: 10132
  selector:
      name: nextcloud
