apiVersion: v1
kind: Deployment
metadata:
 name: nextcloud
  labels:
    name: nextcloud
spec:
  replicas: 1
  selector:
    name: nextcloud
  template:
    metadata:
      labels:
        name: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nexcloud:latest
          ports:
            - containerPort: 10131
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/
          env:
            - name: MYSQL_HOST
              value: "<host>"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              secretKeyRef:
                key: MYSQL_ROOT_PASSWORD
                name: db-secrets
            - name: MYSQL_DATABASE
              value: "nextcloud"
      volumes:
        - name: nextcloud-data
          hostPath:
            path: /var/www/nextcloud
