apiVersion: v1
kind: Service
metadata:
  name: humhub
  labels:
    name: humhub
spec:
  ports:
    - port: 80
      targetPort: 10111
    - port: 443
      targetPort: 10112
  selector:
      name: humhub
