apiVersion: v1
kind: Deployment
metadata:
 name: humhub
  labels:
    name: humhub
spec:
  replicas: 1
  selector:
    name: humhub
  template:
    metadata:
      labels:
        name: humhub
    spec:
      containers:
        - name: humhub
          image: mriedmann/humhub:1.4.4
          ports:
            - containerPort: 10111
          volumeMounts:
            - name: humhub-data
              mountPath: /var/www/humhub
          env:
            - name: HUMHUB_DB_USER
              value: "root"
            - name: HUMHUB_DB_PASSWORD
              secretKeyRef:
                key: MYSQL_ROOT_PASSWORD
                name: db-secrets
            - name: HUMHUB_DB_HOST
              value: "<host>"
            - name: HUMHUB_DB_NAME
              value: "humhub"
            - name: HUMHUB_PROTO
              value: "https"
            - name: HUMHUB_HOST
              value: "<hostname>"
      volumes:
        - name: humhub-data
          hostPath:
            path: /var/www/humhub
