apiVersion: v1
kind: Service
metadata:
  name: mailinabox
  labels:
    name: mailinabox
spec:
  ports:
    - port: 80
      targetPort: 10121
    - port: 443
      targetPort: 10122
    - port: 25
      targetPort: 10123
    - port: 587
      targetPort: 10124
    - port: 993
      targetPort: 10125
    - port: 995
      targetPort: 10126
    - port: 4190
      targetPort: 10127
  selector:
      name: mailinabox
